### ISSUE TITLE
"Crunt" question needs putting back in.

### ISSUE THREAD

**Issue by rymawby** [theSmaw/interview-questions#1]
Please put Crunt back in

**Comment by theSmaw** [comment]
Is it Done done?

**Comment by rymawby** [comment]
Nope.

**Comment by rymawby** [comment]
I had it open for 6 years so thought I might as well close it.

**Comment by theSmaw** [comment]
One can refractor it later.

**Comment by rymawby** [comment]
This is vrery true indreed.
